phrase:
  project_id: 9d39d46187677e605fc2227a9f3f95ca
  file_format: stringsdict
  push:
    sources:
    - file: ./Localizable.stringsdict
      params:
        file_format: stringsdict
        locale_id: a283846c3b24fbe81eb1df807263d039
  pull:
    targets:
    - file: ./Localizable.stringsdict
      params:
        file_format: stringsdict
        locale_id: a283846c3b24fbe81eb1df807263d039
